### ISSUE TITLE
Edge case testing

### ISSUE THREAD

**Issue by 0xm3rlin** [Abracadabra-money/abracadabra-ui#24]
https://github.com/Abracadabra-money/abracadabra-ui/blob/71bcade74b1878676cf0293d28672d3ae8d54571/src/mixins/borrow/cauldrons.js#L331

What happens in the case a user has an allowance > 0 but smaller than the amount he wants to deposit.

Please add a test for such a scenario

**Comment by 0xhardrefresh** [comment]
Checking the allowance has been updated, here example:

https://github.com/Abracadabra-money/abracadabra-ui/blob/main/src/helpers/cauldron/validators.ts#L365
