### ISSUE TITLE
Positions page using stale price on cauldron contract

### ISSUE THREAD

**Issue by 0xidkfa** [Abracadabra-money/abracadabra-ui#89]
Feels like we should be using the oracleExchangeRate all the time, even when the contractExchangeRate is higher, as the oracleExchangeRate is considered to be the truth.

https://github.com/Abracadabra-money/abracadabra-ui/blob/71ca3d15b49bf99f9a3e1528915e03d09b6a8e25/src/mixins/borrow/cauldrons.js#L736-L741

**Comment by 0xhardrefresh** [comment]
It's fixed now

https://github.com/Abracadabra-money/abracadabra-ui/blob/main/src/helpers/cauldron/getMainParams.ts#L47
